#!/usr/bin/env python3
"""
aggregate_project_context.py
将项目中所有 .py 文件的前 N 行代码聚合到单个文件中，
用于 AI 辅助的项目设计哲学分析。
"""

import os
from pathlib import Path


def aggregate_python_files(
    root_dir: str = ".",
    output_file: str = "_project_context_aggregated.py",
    max_lines: int = 100,
    exclude_dirs: set[str] | None = None,
) -> Path:
    """
    扫描目录下所有 .py 文件，提取前 max_lines 行写入汇总文件。

    Args:
        root_dir: 项目根目录
        output_file: 输出文件名
        max_lines: 每个文件最多提取的行数
        exclude_dirs: 需要排除的目录名集合
    Returns:
        生成的汇总文件路径
    """
    if exclude_dirs is None:
        exclude_dirs = {
            "__pycache__", ".git", ".venv", "venv",
            "node_modules", ".tox", ".mypy_cache",
            ".pytest_cache", "dist", "build", "*.egg-info",
        }

    root_path = Path(root_dir).resolve()
    output_path = root_path / output_file
    py_files = sorted([
        p for p in root_path.rglob("*.py")
        if not any(excluded in p.parts for excluded in exclude_dirs)
        and p.name != output_file  # 排除输出文件自身
    ])

    with open(output_path, "w", encoding="utf-8") as out:
        # 写入头部索引
        out.write(f"# {'=' * 70}\n")
        out.write(f"# PROJECT CONTEXT AGGREGATE\n")
        out.write(f"# Root: {root_path}\n")
        out.write(f"# Total .py files: {len(py_files)}\n")
        out.write(f"# Lines per file: <= {max_lines}\n")
        out.write(f"# Generated by: aggregate_python_files()\n")
        out.write(f"# {'=' * 70}\n\n")

        # 写入文件索引目录
        out.write("# FILE INDEX:\n")
        for i, fpath in enumerate(py_files, 1):
            rel = fpath.relative_to(root_path)
            out.write(f"#   {i:3d}. {rel}\n")
        out.write(f"\n# {'=' * 70}\n\n")

        # 逐文件提取内容
        for fpath in py_files:
            rel = fpath.relative_to(root_path)
            out.write(f"\n# >>>>>> FILE: {rel} <<<<<<\n")
            try:
                with open(fpath, "r", encoding="utf-8", errors="replace") as f:
                    lines = []
                    for idx, line in enumerate(f):
                        if idx >= max_lines:
                            lines.append(f"# ... [truncated after {
                                         max_lines} lines] ...\n")
                            break
                        lines.append(line)
                    out.writelines(lines)
            except Exception as e:
                out.write(f"# [ERROR reading file: {e}]\n")
            out.write(f"# >>>>>> END: {rel} <<<<<<\n\n")

    print(f"✅ Aggregated {len(py_files)} files → {output_path}")
    print(f"   Size: {output_path.stat().st_size / 1024:.1f} KB")
    return output_path


if __name__ == "__main__":
    # 在项目根目录下直接运行即可
    aggregate_python_files()
